/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author s.lucas
 */
public class Guru extends javax.swing.JFrame {

    /**
     * Creates new form Guru
     */
    public Guru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 1, 48)); // NOI18N
        jLabel1.setText("Guru Online");

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        jLabel2.setText("Nome");

        txtNome.setForeground(new java.awt.Color(153, 102, 255));

        jLabel3.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        jLabel3.setText("Sexo");

        txtSexo.setForeground(new java.awt.Color(153, 102, 255));

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        jLabel4.setText("Dia de nascimento");

        txtDia.setForeground(new java.awt.Color(153, 102, 255));

        jLabel5.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        jLabel5.setText("Mês de nascimento");

        txtMes.setForeground(new java.awt.Color(153, 102, 255));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        jLabel6.setText("Ano de nascimento");

        txtAno.setForeground(new java.awt.Color(153, 102, 255));

        btnVerificar.setBackground(new java.awt.Color(102, 255, 102));
        btnVerificar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVerificar.setText("Play");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(255, 0, 0));
        btnLimpar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9081716_zodiac_virgo_icon.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737214_astrology_horoscope_scorpio_zodiac_zodiac sign_icon.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737206_astrology_horoscope_libra_zodiac_zodiac sign_icon.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737213_astrology_horoscope_pisces_zodiac_zodiac sign_icon.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737216_astrology_gemeni_horoscope_zodiac_zodiac sign_icon.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737210_aquarius_astrology_horoscope_zodiac_zodiac sign_icon.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737212_astrology_horoscope_sagitaurius_zodiac_zodiac sign_icon.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737211_astrology_capricorn_horoscope_zodiac_zodiac sign_icon.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737217_aries_astrology_horoscope_zodiac_zodiac sign_icon.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737208_astrology_horoscope_taurus_zodiac_zodiac sign_icon.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737209_astrology_horoscope_leo_zodiac_zodiac sign_icon.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1737207_astrology_cancer_horoscope_zodiac_zodiac sign_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(445, 445, 445))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(49, 49, 49))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addComponent(jLabel8)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(54, 54, 54)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(btnLimpar))
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(167, 167, 167))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel7)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel18)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnVerificar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpar)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText(null);
        txtDia.setText(null);
        txtMes.setText(null);
        txtAno.setText(null);
        txtSexo.setText(null);

        JOptionPane.showMessageDialog(null, "me desapareço");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        String nome, sexo;
        nome = txtNome.getText();
        int mes, dia, ano, numSorte, idade, anoA;
        boolean bissexto = false, masculino = false, feminino = false;
        Calendar hoje = Calendar.getInstance();
        sexo = txtSexo.getText();
        dia = Integer.parseInt(txtDia.getText());
        mes = Integer.parseInt(txtMes.getText());
        ano = Integer.parseInt(txtAno.getText());
        anoA = hoje.get(Calendar.YEAR);
        idade = anoA - ano;
        int sorte;
        sorte = (int) 1 + (int) (Math.random() * 100);
        if (sexo.equals("Masculino") || sexo.equals("M") || sexo.equals("masculino") || sexo.equals("m")) {
            masculino = true;
        } else if (sexo.equals("Feminino") || sexo.equals("F") || sexo.equals("feminino") || sexo.equals("f")) {
            feminino = true;
        } else if(sexo.equals("gosto")){
            JOptionPane.showMessageDialog(null,"Eu também!");
            
        }

        if (nome.length() < 8) {
            JOptionPane.showMessageDialog(null, "esse nome não existe vida");
        }
        if (ano % 400 == 0) {
            bissexto = true;
        } else if (bissexto == false && mes == 2 && dia > 28) {
            JOptionPane.showMessageDialog(null, "O ano não é bissexto");

        } else if ((mes == 4 && dia > 30) || (mes == 6 && dia > 30) || (mes == 9 && dia > 30) || (mes == 11 && dia > 30)) {
            JOptionPane.showMessageDialog(null, "Esse mes possui apenas 30 dias");

        }
        if (ano < 1900) {
            JOptionPane.showMessageDialog(null, "com certeza você nasceu nesse ano");
        } else if (dia == 21 && mes == 3 || dia == 20 && mes == 4&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Áries\n Seu número da sorte é: " + sorte + "\n Sua cor é: vermelho");
        } else if (dia >= 21 && mes == 4 || dia <= 20 && mes == 5&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Touro\n Seu número da sorte é: " + sorte + "\n Sua cor é: verde");
        } else if (dia >= 21 && mes == 5 || dia <= 20 && mes == 6&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Gêmeos\n Seu número da sorte é: " + sorte + "\n Sua cor é: amarelo");
        } else if (dia >= 21 && mes == 6 || dia <= 21 && mes == 7&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Câncer\n Seu número da sorte é: " + sorte + "\n Sua cor é: prata");
        } else if (dia >= 22 && mes == 7 || dia <= 22 && mes == 8&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Leão\n Seu número da sorte é: " + sorte + "\n Sua cor é: laranja");
        } else if (dia >= 23 && mes == 8 || dia <= 22 && mes == 9&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Virgem\n Seu número da sorte é: " + sorte + "\n Sua cor é: marrom");
        } else if (dia >= 23 && mes == 9 || dia <= 22 && mes == 10&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Libra\n Seu número da sorte é: " + sorte + "\n Sua cor é: rosa");
        } else if (dia >= 23 && mes == 10 || dia <= 21 && mes == 11&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Escorpião\n Seu número da sorte é: " + sorte + "\n Sua cor é: branco");
        } else if (dia >= 22 && mes == 11 || dia <= 21 && mes == 12&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Sagitarion\n Seu número da sorte é: " + sorte + "\n Sua cor é: dourado");
        } else if (dia >= 22 && mes == 12 || dia <= 20 && mes == 1&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Capricórnio\n Seu número da sorte é: " + sorte + "\n Sua cor é: roxo");
        } else if (dia >= 21 && mes == 1 || dia <= 19 && mes == 2&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Aquário\n Seu número da sorte é: " + sorte + "\n Sua cor é: azul");
        } else if (dia >= 20 && mes == 2 || dia <= 20 && mes == 3&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Peixes\n Seu número da sorte é: " + sorte + "\n Sua cor é: salmão");
        } 
        else if (dia == 21 && mes == 3 || dia == 20 && mes == 4&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Áries\n Seu número da sorte é: " + sorte + "\n Sua cor é: vermelho");
        } else if (dia >= 21 && mes == 4 || dia <= 20 && mes == 5&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Touro\n Seu número da sorte é: " + sorte + "\n Sua cor é: verde");
        } else if (dia >= 21 && mes == 5 || dia <= 20 && mes == 6&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Gêmeos\n Seu número da sorte é: " + sorte + "\n Sua cor é: amarelo");
        } else if (dia >= 21 && mes == 6 || dia <= 21 && mes == 7&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Câncer\n Seu número da sorte é: " + sorte + "\n Sua cor é: prata");
        } else if (dia >= 22 && mes == 7 || dia <= 22 && mes == 8&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Leão\n Seu número da sorte é: " + sorte + "\n Sua cor é: laranja");
        } else if (dia >= 23 && mes == 8 || dia <= 22 && mes == 9&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Virgem\n Seu número da sorte é: " + sorte + "\n Sua cor é: marrom");
        } else if (dia >= 23 && mes == 9 || dia <= 22 && mes == 10&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Libra\n Seu número da sorte é: " + sorte + "\n Sua cor é: rosa");
        } else if (dia >= 23 && mes == 10 || dia <= 21 && mes == 11&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Escorpião\n Seu número da sorte é: " + sorte + "\n Sua cor é: branco");
        } else if (dia >= 22 && mes == 11 || dia <= 21 && mes == 12&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Sagitarion\n Seu número da sorte é: " + sorte + "\n Sua cor é: dourado");
        } else if (dia >= 22 && mes == 12 || dia <= 20 && mes == 1&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Capricórnio\n Seu número da sorte é: " + sorte + "\n Sua cor é: roxo");
        } else if (dia >= 21 && mes == 1 || dia <= 19 && mes == 2&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Aquário\n Seu número da sorte é: " + sorte + "\n Sua cor é: azul");
        } else if (dia >= 20 && mes == 2 || dia <= 20 && mes == 3&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Peixes\n Seu número da sorte é: " + sorte + "\n Sua cor é: salmão");
        
        
        

    }//GEN-LAST:event_btnVerificarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
