/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author s.lucas
 */
public class Guru extends javax.swing.JFrame {

    /**
     * Creates new form Guru
     */
    public Guru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Guru Online");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Sexo");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Dia de nascimento");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Mês de nascimento");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Ano de nascimento");

        btnVerificar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnVerificar)
                        .addGap(52, 52, 52)
                        .addComponent(btnLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerificar)
                    .addComponent(btnLimpar))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText(null);
        txtDia.setText(null);
        txtMes.setText(null);
        txtAno.setText(null);
        txtSexo.setText(null);

        JOptionPane.showMessageDialog(null, "tudo limpo, dos meu");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        String nome, sexo;
        nome = txtNome.getText();
        int mes, dia, ano, numSorte, idade, anoA;
        boolean bissexto = false, masculino = false, feminino = false;
        Calendar hoje = Calendar.getInstance();
        sexo = txtSexo.getText();
        dia = Integer.parseInt(txtDia.getText());
        mes = Integer.parseInt(txtMes.getText());
        ano = Integer.parseInt(txtAno.getText());
        anoA = hoje.get(Calendar.YEAR);
        idade = anoA - ano;
        int sorte;
        sorte = (int) 1 + (int) (Math.random() * 100);
        if (sexo.equals("Masculino") || sexo.equals("M") || sexo.equals("masculino") || sexo.equals("m")) {
            masculino = true;
        } else if (sexo.equals("Feminino") || sexo.equals("F") || sexo.equals("feminino") || sexo.equals("f")) {
            feminino = true;
        } else if(sexo.equals("gosto")){
            JOptionPane.showMessageDialog(null,"Eu também!");
            
        }

        if (nome.length() < 8) {
            JOptionPane.showMessageDialog(null, "seria legal se fosse seu nome verdadeiro");
        }
        if (ano % 400 == 0) {
            bissexto = true;
        } else if (bissexto == false && mes == 2 && dia > 28) {
            JOptionPane.showMessageDialog(null, "O ano não é bissexto");

        } else if ((mes == 4 && dia > 30) || (mes == 6 && dia > 30) || (mes == 9 && dia > 30) || (mes == 11 && dia > 30)) {
            JOptionPane.showMessageDialog(null, "Esse mes possui apenas 30 dias");

        }
        if (ano < 1900) {
            JOptionPane.showMessageDialog(null, "com certeza você nasceu nesse ano");
        } else if (dia == 21 && mes == 3 || dia == 20 && mes == 4&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Áries\n Seu número da sorte é: " + sorte + "\n Sua cor é: vermelho");
        } else if (dia >= 21 && mes == 4 || dia <= 20 && mes == 5&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Touro\n Seu número da sorte é: " + sorte + "\n Sua cor é: verde");
        } else if (dia >= 21 && mes == 5 || dia <= 20 && mes == 6&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Gêmeos\n Seu número da sorte é: " + sorte + "\n Sua cor é: amarelo");
        } else if (dia >= 21 && mes == 6 || dia <= 21 && mes == 7&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Câncer\n Seu número da sorte é: " + sorte + "\n Sua cor é: prata");
        } else if (dia >= 22 && mes == 7 || dia <= 22 && mes == 8&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Leão\n Seu número da sorte é: " + sorte + "\n Sua cor é: laranja");
        } else if (dia >= 23 && mes == 8 || dia <= 22 && mes == 9&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Virgem\n Seu número da sorte é: " + sorte + "\n Sua cor é: marrom");
        } else if (dia >= 23 && mes == 9 || dia <= 22 && mes == 10&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Libra\n Seu número da sorte é: " + sorte + "\n Sua cor é: rosa");
        } else if (dia >= 23 && mes == 10 || dia <= 21 && mes == 11&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Escorpião\n Seu número da sorte é: " + sorte + "\n Sua cor é: branco");
        } else if (dia >= 22 && mes == 11 || dia <= 21 && mes == 12&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Sagitarion\n Seu número da sorte é: " + sorte + "\n Sua cor é: dourado");
        } else if (dia >= 22 && mes == 12 || dia <= 20 && mes == 1&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Capricórnio\n Seu número da sorte é: " + sorte + "\n Sua cor é: roxo");
        } else if (dia >= 21 && mes == 1 || dia <= 19 && mes == 2&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Aquário\n Seu número da sorte é: " + sorte + "\n Sua cor é: azul");
        } else if (dia >= 20 && mes == 2 || dia <= 20 && mes == 3&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é homem\n Seu signo é Peixes\n Seu número da sorte é: " + sorte + "\n Sua cor é: salmão");
        } 
        else if (dia == 21 && mes == 3 || dia == 20 && mes == 4&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Áries\n Seu número da sorte é: " + sorte + "\n Sua cor é: vermelho");
        } else if (dia >= 21 && mes == 4 || dia <= 20 && mes == 5&&masculino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Touro\n Seu número da sorte é: " + sorte + "\n Sua cor é: verde");
        } else if (dia >= 21 && mes == 5 || dia <= 20 && mes == 6&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Gêmeos\n Seu número da sorte é: " + sorte + "\n Sua cor é: amarelo");
        } else if (dia >= 21 && mes == 6 || dia <= 21 && mes == 7&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Câncer\n Seu número da sorte é: " + sorte + "\n Sua cor é: prata");
        } else if (dia >= 22 && mes == 7 || dia <= 22 && mes == 8&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Leão\n Seu número da sorte é: " + sorte + "\n Sua cor é: laranja");
        } else if (dia >= 23 && mes == 8 || dia <= 22 && mes == 9&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Virgem\n Seu número da sorte é: " + sorte + "\n Sua cor é: marrom");
        } else if (dia >= 23 && mes == 9 || dia <= 22 && mes == 10&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Libra\n Seu número da sorte é: " + sorte + "\n Sua cor é: rosa");
        } else if (dia >= 23 && mes == 10 || dia <= 21 && mes == 11&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Escorpião\n Seu número da sorte é: " + sorte + "\n Sua cor é: branco");
        } else if (dia >= 22 && mes == 11 || dia <= 21 && mes == 12&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Sagitarion\n Seu número da sorte é: " + sorte + "\n Sua cor é: dourado");
        } else if (dia >= 22 && mes == 12 || dia <= 20 && mes == 1&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Capricórnio\n Seu número da sorte é: " + sorte + "\n Sua cor é: roxo");
        } else if (dia >= 21 && mes == 1 || dia <= 19 && mes == 2&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Aquário\n Seu número da sorte é: " + sorte + "\n Sua cor é: azul");
        } else if (dia >= 20 && mes == 2 || dia <= 20 && mes == 3&&feminino==true) {
            JOptionPane.showMessageDialog(null, "Ola " + nome + ", você tem " + idade + " anos.\n Vocé é mulher\n Seu signo é Peixes\n Seu número da sorte é: " + sorte + "\n Sua cor é: salmão");
        
        
        

    }//GEN-LAST:event_btnVerificarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
